## Create an array

In [3]:
import numpy as np

In [4]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [5]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [9]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [15]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [17]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [19]:
np.random.rand(2,4)

array([[0.9055997 , 0.34629071, 0.74804492, 0.35956953],
       [0.88044701, 0.90914747, 0.73092294, 0.96668952]])

In [20]:
np.random.randn(2,4)

array([[-0.42772447, -0.87754214, -0.98505961,  0.263687  ],
       [-1.26790386, -0.57929186, -0.92671069,  0.22139546]])

In [21]:
np.random.rand(2,5)

array([[0.41882757, 0.23124476, 0.31879159, 0.19690573, 0.94845448],
       [0.70013081, 0.92812143, 0.02686201, 0.54275541, 0.11982706]])

In [22]:
np.random.randint(10,100,15)

array([74, 51, 62, 30, 68, 71, 31, 22, 94, 87, 66, 11, 11, 44, 35])

In [23]:
np.random.randint(20,56,100)

array([30, 34, 29, 22, 32, 51, 33, 27, 45, 50, 24, 25, 37, 23, 28, 23, 40,
       51, 43, 35, 46, 46, 55, 47, 39, 39, 53, 20, 35, 38, 32, 28, 38, 47,
       54, 39, 28, 26, 47, 25, 51, 35, 41, 48, 40, 39, 42, 31, 32, 30, 42,
       42, 23, 44, 49, 23, 44, 45, 25, 52, 21, 53, 31, 39, 35, 54, 42, 53,
       21, 24, 41, 47, 49, 45, 33, 34, 32, 55, 52, 27, 47, 25, 38, 42, 23,
       32, 40, 44, 31, 36, 49, 33, 26, 40, 21, 28, 35, 41, 40, 53])

In [ ]:
import numpy as np

In [25]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
rand_array=np.random.randint(0,10,5)
rand_array

array([1, 3, 1, 3, 5])

In [27]:
sample_array.min()

2

In [28]:
sample_array.argmin()      ##index value

0

In [29]:
rand_array.argmin()

0

In [30]:
rand_array.max()

5

In [31]:
rand_array.argmax()

4

In [32]:
sample_array.argmax()

17

In [33]:
sample_array.dtype

dtype('int32')

In [34]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
a=np.random.rand(2,3)
a

array([[0.09102111, 0.13961441, 0.93937972],
       [0.5960757 , 0.99011425, 0.89554355]])

In [38]:
a.T

array([[0.09102111, 0.5960757 ],
       [0.13961441, 0.99011425],
       [0.93937972, 0.89554355]])

In [ ]:
import numpy as np

In [40]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [41]:
sample_array=sample_array.reshape(2,9)
sample_array

array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [42]:
sample_array=sample_array.reshape(3,4)
sample_array

ValueError: cannot reshape array of size 18 into shape (3,4)

In [44]:
sample_array[1]=100
sample_array

array([[ 10,  11,  12,  13,  14,  15,  16,  17,  18],
       [100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [46]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [47]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [48]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [49]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

## Two-Dimentional array

In [ ]:
import numpy as np

In [50]:
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [51]:
sample_matrix[2][2]

24

In [52]:
sample_matrix[1][2]

54

In [53]:
sample_matrix[:,2]

array([ 2, 54, 24])

In [54]:
sample_matrix[1,1]

2

In [56]:
sample_matrix[1:3,2:4]     ## row from index 1 onwards and column from 2 onwards

array([[54, 65],
       [24,  7]])

In [55]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [57]:
sample_matrix[2]

array([56, 76, 24,  7])

In [ ]:
import numpy as np

In [59]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [61]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [62]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [63]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [64]:
np.max(sample_array)

30

In [65]:
np.min(sample_array)

1

In [66]:
np.argmax(sample_array)

29

In [67]:
np.argmin(sample_array)

0

In [68]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [69]:
np.std(sample_array)

8.65544144839919

In [70]:
np.var(sample_array)

74.91666666666667

In [72]:
np.mean(sample_array)

15.5

In [75]:
array=np.random.randn(3,4)       ## uniform distribution
array

array([[ 0.33153035, -0.01752919, -1.30312598, -0.82824523],
       [-2.66206373,  0.10914333, -0.98760716,  0.38644418],
       [ 0.27021868, -0.3833448 , -0.31043231, -0.52117878]])

In [76]:
np.round(array,decimals=3)

array([[ 0.332, -0.018, -1.303, -0.828],
       [-2.662,  0.109, -0.988,  0.386],
       [ 0.27 , -0.383, -0.31 , -0.521]])

In [77]:
sports=np.array(['golf','cricket','fball','cricket','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')

# Pandas

In [ ]:
import pandas as pd

In [79]:
labels=['a','b','c','d']

In [80]:
list=[10,28,3,4]

In [81]:
import numpy as np

In [82]:
array=np.array([1,2,3,4])

In [83]:
dict={'w':10,'x':20,'y':30,'z':40}

In [84]:
pd.Series(data=list)

0    10
1    28
2     3
3     4
dtype: int64

In [85]:
pd.Series(data=list,index=labels)

a    10
b    28
c     3
d     4
dtype: int64

In [86]:
pd.Series(labels,list)

10    a
28    b
3     c
4     d
dtype: object

In [87]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

## Pandas dataframe and indexing

In [88]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [89]:
sports1['basketball']

3

In [90]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [91]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [92]:
import pandas as pd
import numpy as np

In [94]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.199374  0.239587  0.099852  0.541880  0.381712
B  0.966601  0.429850  0.192387  0.974094  0.601765
C  0.666724  0.153223  0.230356  0.753178  0.484331
D  0.398280  0.021987  0.891482  0.564474  0.670158
E  0.969958  0.688025  0.556212  0.547938  0.101073
F  0.760987  0.034240  0.348422  0.210848  0.906353
G  0.662148  0.174817  0.443940  0.615395  0.685335
H  0.340585  0.999567  0.564041  0.413827  0.775963

In [95]:
df1[{'score2','score3','score5'}]

score2    score5    score3
A  0.239587  0.381712  0.099852
B  0.429850  0.601765  0.192387
C  0.153223  0.484331  0.230356
D  0.021987  0.670158  0.891482
E  0.688025  0.101073  0.556212
F  0.034240  0.906353  0.348422
G  0.174817  0.685335  0.443940
H  0.999567  0.775963  0.564041

In [96]:
df1['score6']=df1['score1']-df1['score2']
df1

score1    score2    score3    score4    score5    score6
A  0.199374  0.239587  0.099852  0.541880  0.381712 -0.040214
B  0.966601  0.429850  0.192387  0.974094  0.601765  0.536751
C  0.666724  0.153223  0.230356  0.753178  0.484331  0.513501
D  0.398280  0.021987  0.891482  0.564474  0.670158  0.376293
E  0.969958  0.688025  0.556212  0.547938  0.101073  0.281934
F  0.760987  0.034240  0.348422  0.210848  0.906353  0.726747
G  0.662148  0.174817  0.443940  0.615395  0.685335  0.487331
H  0.340585  0.999567  0.564041  0.413827  0.775963 -0.658982

In [97]:
df1.drop('score5',axis=1)

score1    score2    score3    score4    score6
A  0.199374  0.239587  0.099852  0.541880 -0.040214
B  0.966601  0.429850  0.192387  0.974094  0.536751
C  0.666724  0.153223  0.230356  0.753178  0.513501
D  0.398280  0.021987  0.891482  0.564474  0.376293
E  0.969958  0.688025  0.556212  0.547938  0.281934
F  0.760987  0.034240  0.348422  0.210848  0.726747
G  0.662148  0.174817  0.443940  0.615395  0.487331
H  0.340585  0.999567  0.564041  0.413827 -0.658982

In [98]:
df1.drop("E")

score1    score2    score3    score4    score5    score6
A  0.199374  0.239587  0.099852  0.541880  0.381712 -0.040214
B  0.966601  0.429850  0.192387  0.974094  0.601765  0.536751
C  0.666724  0.153223  0.230356  0.753178  0.484331  0.513501
D  0.398280  0.021987  0.891482  0.564474  0.670158  0.376293
F  0.760987  0.034240  0.348422  0.210848  0.906353  0.726747
G  0.662148  0.174817  0.443940  0.615395  0.685335  0.487331
H  0.340585  0.999567  0.564041  0.413827  0.775963 -0.658982

In [99]:
df2={'ID':[101,102,103,107,176],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

### Assignments
1. Create a null vector of size 10
2. Create a null vector of size 10 but the fifth value should be one
3. Create a vector with values ranging from10 to 65
4. reverse the above vector
5. Create a 3*3 matrix with values ranging from 0 to 8

In [100]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [101]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [102]:
z=np.arange(10,66)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [103]:
z[::-1]

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [106]:
z=np.arange(65,9,-1)
z

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [107]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])